version: '3'

services:
  fpm:
    build: php${PHP_VERSION}/fpm
    depends_on:
      - mariadb
      - redis
    volumes:
      - ./project:/var/www/project

  cli:
    build: php${PHP_VERSION}/cli
    working_dir: /var/www/project
    volumes:
      - ./project:/var/www/project
    depends_on:
      - mariadb
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./project:/var/www/project
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - fpm

  redis:
    image: redis:alpine
  
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    ports:
      - ${MARIADB_PORT}:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE_NAME}
      # - MYSQL_USER=admin
      # - MYSQL_PASSWORD=admin
      - TERM=meh

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
      # - PMA_ARBITRARY=1
    links:
      - mariadb
    ports:
      - ${PHPMYADMIN_PORT}:80
