version: '3'
services:
  fpm:
    image: readymadehost/symfony-dev-docker-php${PHP_VERSION}-fpm:${DOCKER_TAG}
    build:
      context: php${PHP_VERSION}/fpm
      args:
        PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
        PHP_ENABLE_AMQP: ${PHP_ENABLE_AMQP}
        PHP_ENABLE_REDIS: ${PHP_ENABLE_REDIS}
    environment:
      PHP_ENABLE_AMQP: ${PHP_ENABLE_AMQP}
      PHP_ENABLE_REDIS: ${PHP_ENABLE_REDIS}
      PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    ports:
      - ${PHP_FPM_PORT}:9000
    volumes:
      - ./project:/var/www/project
    depends_on:
      - mariadb
      - redis

  cli:
    image: readymadehost/symfony-dev-docker-php${PHP_VERSION}-cli:${DOCKER_TAG}
    build:
      context: php${PHP_VERSION}/cli
      args:
        PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
        PHP_ENABLE_AMQP: ${PHP_ENABLE_AMQP}
        PHP_ENABLE_REDIS: ${PHP_ENABLE_REDIS}
    environment:
      PHP_ENABLE_AMQP: ${PHP_ENABLE_AMQP}
      PHP_ENABLE_REDIS: ${PHP_ENABLE_REDIS}
      PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    working_dir: /var/www/project
    volumes:
      - ./project:/var/www/project
    depends_on:
      - mariadb
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./project:/var/www/project
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
    environment:
      - PHP_FPM_PORT=${PHP_FPM_PORT}
    depends_on:
      - fpm

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    ports:
      - ${MARIADB_PORT}:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE_NAME}
      - TERM=meh

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_ARBITRARY=1
    links:
      - mariadb
    ports:
      - ${PHPMYADMIN_PORT}:80

  redis:
    image: redis:alpine

